add (Leitung): Leistung and Vorgehen Smith chart
ayham291/FWL_Formelsammlung pull request #53
Opened 2022-07-07 13:59 UTC by josero360

2022-07-07 15:19 UTC, m4nshaman requested changes

2022-07-07 15:19 UTC, m4nshaman commented on Smithdiagramm.tex
> +    \item Lastimpedanz Bestimmen
Schritt ein unverständlich. Lastimpedanz wird nicht bestimmt sondern mit Z_A verrechnet und dann eingetragen außer Z_L->inf

2022-07-07 15:38 UTC, josero360 commented on Smithdiagramm.tex
> +    \item Lastimpedanz Bestimmen
Das ist vorbereitet das du mehrere Elemente in reihe oder parallel hast. Und die dann erstmal zusammen rechnest.
Wenn du nur ein Element hast ist das (hoffentlich) von der Aufgabe gegeben

2022-07-08 21:34 UTC, ayham291 approved these changes

2022-07-08 21:35 UTC, merged